### PR TITLE
Not using exceptions for flow control if suppress exceptions is enabled

### PR DESCRIPTION
**Pull request by r0goyal**

### CODE REVIEW

**Comment by r0goyal** [comment]
@kallestenflo Requesting your approval for this

**Comment by abelsromero** [comment]
This has introduced breaking changes in 2.7.0 vs 2.6.0. For instance now `set` throws and exception when the path is not present in the target JSON.
I can't find any explanation of why this change was introduced or whether the project follows semantic versioning, so I'd really appreciate some clarification on those topics 🙇

**Comment by ailjushkin** [comment]
@r0goyal @abelsromero  Maybe we should add an option to create an absent path, to handle each of use cases. But at least I'd wanted to get any ideas which problem this PR is solving to get more context on this.

**Comment by jslopez-forum** [comment]
I found another change in behavior from this change.  The following snippet used to return null under 2.6.0 and it now fails under 2.7.0. Since SUPPRESS_EXCEPTIONS is configured, I would have expected no exceptions to be propagated.

```java
        final String json = "{\"value\" :  null" + "}";
        final Configuration configuration = Configuration.builder()
                .jsonProvider(new JsonOrgJsonProvider())
                .mappingProvider(new JsonOrgMappingProvider())
                .options(Option.SUPPRESS_EXCEPTIONS).build();
        String value = JsonPath.using(configuration).parse(json).read("$.value");
        System.out.println(value);
```

2.6.0 value = null
2.7.0
```java
Exception in thread "main" com.jayway.jsonpath.JsonPathException: org.json.JSONException: JSONArray[0] not found.
	at com.jayway.jsonpath.spi.json.JsonOrgJsonProvider.getArrayIndex(JsonOrgJsonProvider.java:75)
	at com.jayway.jsonpath.internal.path.EvaluationContextImpl.getValue(EvaluationContextImpl.java:145)
	at com.jayway.jsonpath.JsonPath.read(JsonPath.java:199)
	at com.jayway.jsonpath.internal.JsonContext.read(JsonContext.java:88)
	at com.jayway.jsonpath.internal.JsonContext.read(JsonContext.java:77)
	at Scratch.main(scratch_1.java:15)
Caused by: org.json.JSONException: JSONArray[0] not found.
	at org.json.JSONArray.get(JSONArray.java:209)
	at com.jayway.jsonpath.spi.json.JsonOrgJsonProvider.getArrayIndex(JsonOrgJsonProvider.java:73)
	... 5 more
```

**Comment by abelsromero** [comment]
My main concern with this is the "surprise factor" at the end of the day, we dealt with it, but after some head bashing.
Being blunt here, apologies in advance, "are breaking changes possible in any version release?"

**Comment by mpassell** [comment]
@kallestenflo I just hit this issue as well when trying to upgrade from v2.6.0 to v2.7.0+ (v2.9.0, to be specific). Based on how `JsonPath.handleMissingPathInContext()` was implemented, it can cause a different type to be returned by `JsonPath.put()`, which then causes a `ClassCastException` in `JsonContext.put()`. Based on that, I don't see how I can restore the behavior I had in v2.6.0 no matter which Options I enable.

**Pull request merged**
