### PR TITLE
[build] Remove deprecated gradle convetion usage

### PR DESCRIPTION
**Pull request by shoothzj**
For more context, we can see https://docs.gradle.org/8.2/userguide/upgrading_version_8.html#java_convention_deprecation

### CODE REVIEW

**Comment by Shoothzj** [comment]
@nizhikov could you please take a look?

**Comment by Shoothzj** [comment]
@kallestenflo Could you please take a look?

**Comment by Shoothzj** [comment]
@kallestenflo Could you please take a look?

**Comment by Shoothzj** [comment]
@kallestenflo Could you please take a look?

**Comment by Shoothzj** [comment]
@kallestenflo Could you please take a look?

**Comment by Shoothzj** [comment]
@kallestenflo Could you please take a look?

**Comment by shoothzj** [comment]
@kallestenflo Could you please take a look?

**Pull request merged**
