### PR TITLE
Bump json-smart version from 2.4.10 to 2.5.0

### PR DESCRIPTION
**Pull request by shoothzj**

### CODE REVIEW

**Comment by Shoothzj** [comment]
@kallestenflo Could you please take a look?

**Comment by Shoothzj** [comment]
@kallestenflo Could you please take a look?

**Comment by Shoothzj** [comment]
@kallestenflo Could you please take a look?

**Comment by Shoothzj** [comment]
@kallestenflo Could you please take a look?

**Comment by shoothzj** [comment]
@kallestenflo Could you please take a look?

**Pull request merged**
